#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='vi'
if [[ $TERM = emacs ]]; then
    export PAGER='colcrt'
else
    export PAGER='less'
fi

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nano'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nano'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  $path
  $HOME/.local/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-F -i -M -R -S -X'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -x /usr/local/bin/lesspipe.sh ]]; then
  # eval "$(/usr/local/bin/lesspipe.sh 2>&-)"
  export LESSOPEN="|LC_TIME=C /usr/local/bin/lesspipe.sh %s"
elif (( $+commands[src-hilite-lesspipe.sh] )); then
  export LESSOPEN="|src-hilite-lesspipe.sh %s 2>&-"
elif [[ -x /usr/share/source-highlight/src-hilite-lesspipe.sh ]]; then
  export LESSOPEN="|/usr/share/source-highlight/src-hilite-lesspipe.sh %s 2>&-"
elif [[ -n $commands[(i)lesspipe(|.sh)] ]]; then
  export LESSOPEN="|$commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ -f ~/.ls_colors ]]; then
  export LS_COLORS="$(cat ~/.ls_colors)"
elif (( $+commands[dircolors] )); then
  () {
    local _ls_colors_candidate=(
      ~/.dir_colors
      ~/ghq/github.com/trapd00r/LS_COLORS/LS_COLORS
    )
    local _ls_colors
    local _file
    for _file in $_ls_colors_candidate; do
      if [[ -f $_file ]]; then
        _ls_colors=$_file
        break
      fi
    done
    if (( $+_ls_colors )); then
      eval "$(dircolors -b $_ls_colors)"
      export LSCOLORS='exfxcxdxbxGxDxabagacad'
    fi
  }
fi

if [[ $OSTYPE =~ 'freebsd' ]]; then
  export SSL_CA_CERT_PATH=/etc/ssl/certs
fi

export DICTIONARY=en_US
export TOP=-P

if (( $+commands[fzf] )); then
  export FZF_DEFAULT_OPTS='--multi --bind ctrl-a:select-all --bind ctrl-u:deselect-all'
fi

if (( $+commands[npm] )); then
  export NODE_PATH=$(npm root -g)
fi

# Local Variables:
# mode: sh
# sh-shell: zsh
# sh-basic-offset: 2
# End:
